apiVersion: v1
kind: Service
metadata:
  name: diploma-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: diploma-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
